### ISSUE TITLE
Authentification à l'API Meetup.com

### ISSUE THREAD

**Issue by camillebaronnet** [ArdechDromDev/website#13]
Problème lié au CORS policy, d'après ce que j'ai pu comprendre il faut passer par un système d'authentification :

https://www.meetup.com/fr-FR/meetup_api/auth/

Je peux me tromper mais l'OAuth2 me parait pas adapter à notre besoin et dans un même temps les autres méthodes ne semble plus être supportées.

**Comment by samsalas** [comment]
L ancienne methode semblait plus facile a faire. Mais pas synchro avec meetup. J ai essayé oauth2 (voir branche feature event) sans vraiment aboutir a un truc potable...

**Comment by samsalas** [comment]
Merci à Dominique, j'ai pu m'en sortir. Encore 2 / 3 trucs à améliorer mais c'est bon.

**Comment by samsalas** [comment]
Merged, issue à fermer
