### ISSUE TITLE
Refactoring des pages pour inclure les réseaux sociaux

### ISSUE THREAD

**Issue by samsalas** [ArdechDromDev/website#18]
Comme ce que j'ai fait pour meetup dans la page événements, on peut ajouter 

- [ ] Le  Youtube dans "replay".
- [ ] Remplacer "Adhésions" par "Contribuez" et y mettre le lien Github.
- [ ] En page d'accueil tous les réseaux.
- [ ] Modifier "Contact" pour y mettre les channels slack, tweeter et facebook, linkedin tout en gardant le formulaire.

Pour rappel 
- Site Internet : https://www.ardechdromdev.org/
- Youtube : https://www.youtube.com/channel/UCGeZ9KihmkrUc_Zq9EcDFUQ
- Slack : https://join.slack.com/t/ardech-drom-dev/shared_invite/enQtNDE5MzQ1NzEwODA3LTRlMzcwNDJlN2M4ZWI1YzIyN2YyMzRkZjI0MGNhYjRhZTNjMDE2ZGQ2YjU0YmU2M2VlN2UwMjhkYmE2ZjkxOGM
- Facebook : https://www.facebook.com/ardechdromdev/
- Twitter : https://twitter.com/ardechdromdev
- Linkedin : https://www.linkedin.com/company/ardechdromdev/

**Comment by camillebaronnet** [comment]
N'hésite pas à découper ça en plusieurs issue car il peut y avoir des discussions, ou sinon à mettre des checkbox sur la liste pour suivre l'avancement de chaque tâche

**Comment by camillebaronnet** [comment]
Maintenant que les réseaux sociaux sont intégrés dans le footer, et donc dans toute les pages, je pense qu'on peut clore cette issue.

**Comment by cbouvat** [comment]
Ok avec @camillebaronnet

**Comment by samsalas** [comment]
Ok !
