### ISSUE TITLE
Evenements ne fonctionnent plus

### ISSUE THREAD

**Issue by camillebaronnet** [ArdechDromDev/website#22]
Visiblement quand il n'y a plus d'events il ne récupère pas non plus la première card "meetup"

**Comment by samsalas** [comment]
Oui, c'est pas top. Encore un problème aux limites qu'on n'a pas testé...

Je pars en vacances pendant 10 jours. Faudrait créer un événement meetup d'ici-là (le 29 par exemple).

Je vais emmener mon PC en vacances, si j'ai le temps je regarderai.

**Comment by camillebaronnet** [comment]
<img width="825" alt="Capture d’écran 2019-05-04 à 13 06 53" src="https://user-images.githubusercontent.com/1884268/57178233-a3328b00-6e6d-11e9-826c-ab81649ce8eb.png">

Ce n'est pas lié aux limites, c'est qu'il n'y a plus d'events à venir.

**Comment by samsalas** [comment]
C'est une facon de parler... ca veut juste dire qu on a pas testé tous les cas. Dont celui ci.
Je ne pourrai pas corriger avant mi mai.

**Comment by cbouvat** [comment]
Je peux fix ?

**Comment by samsalas** [comment]
Fais toi plaisir !

**Comment by GaspardPO** [comment]
c'est corrigé ça non ?
on ferme la PR ?

**Comment by camillebaronnet** [comment]
C'est "corrigé" du fait qu'il y ait un event récurrent, mais visiblement pas parce que le code eu été corrigé

**Comment by dominiqueduplan** [comment]
Corrigé. Désormais la carte du groupe s'affiche même si plus d'event.
